from datetime import datetime
from enum import Enum

from pydantic import BaseModel


class Sender(str, Enum):
    """Who sent the message.

    - USER  — the remote Telegram user, a real human (incoming).
    - AGENT — the human using the back-office app, replying *as the bot*
              (outgoing; this is what the system produces today).
    - BOT   — an automated reply generated by the server. Not produced today;
              reserved as a distinct role for when automation is added.

    AGENT and BOT are both "our side" (right-hand bubbles); USER is the other.
    """

    USER = "user"
    AGENT = "agent"
    BOT = "bot"


class Status(str, Enum):
    # Outgoing lifecycle:
    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"
    # Incoming (constant):
    RECEIVED = "received"


class Message(BaseModel):
    """The single message shape shared by REST responses and WebSocket events.

    `chat_id` is the Telegram conversation it belongs to — a first-class field
    so the system extends from one conversation to many without a reshape.
    """

    id: str
    chat_id: int
    text: str
    timestamp: datetime
    sender: Sender
    status: Status


class SendMessageRequest(BaseModel):
    """Body of POST /messages. The client states which conversation (`chat_id`)
    it is replying to and supplies id/text/timestamp; `sender`/`status` are
    assigned server-side. Unknown fields are ignored."""

    id: str
    chat_id: int
    text: str
    timestamp: datetime
